# Generated by Django 3.0.6 on 2020-05-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200523_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='blog/DownloadsVOZ/'),
        ),
    ]
