# Generated by Django 3.0.6 on 2020-05-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_doi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DOI',
        ),
    ]
